apiVersion: v1
kind: Secret
metadata:
  name: opentube-secrets
type: Opaque
stringData:
  database-admin-user: {{ required "localCredentials.databaseAdminUser is required" .Values.localCredentials.databaseAdminUser | quote }}
  database-admin-password: {{ required "localCredentials.databaseAdminPassword is required" .Values.localCredentials.databaseAdminPassword | quote }}
  identity-password: {{ required "localCredentials.identityPassword is required" .Values.localCredentials.identityPassword | quote }}
  video-password: {{ required "localCredentials.videoPassword is required" .Values.localCredentials.videoPassword | quote }}
  minio-root-user: {{ required "localCredentials.minioRootUser is required" .Values.localCredentials.minioRootUser | quote }}
  minio-root-password: {{ required "localCredentials.minioRootPassword is required" .Values.localCredentials.minioRootPassword | quote }}
  rabbit-user: {{ required "localCredentials.rabbitUser is required" .Values.localCredentials.rabbitUser | quote }}
  rabbit-password: {{ required "localCredentials.rabbitPassword is required" .Values.localCredentials.rabbitPassword | quote }}
  jwt-secret: {{ required "localCredentials.jwtSecret is required" .Values.localCredentials.jwtSecret | quote }}
  worker-token: {{ required "localCredentials.workerToken is required" .Values.localCredentials.workerToken | quote }}
  seed-email: {{ required "localCredentials.seedEmail is required" .Values.localCredentials.seedEmail | quote }}
  seed-password: {{ required "localCredentials.seedPassword is required" .Values.localCredentials.seedPassword | quote }}
